services:
  - type: web
    name: model-verse-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENROUTER_API_KEYS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false

  - type: web
    name: model-verse-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://model-verse-backend.onrender.com 